# Generated by Django 4.1.1 on 2023-07-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneralmodel',
            name='laboratorio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratoriomodel'),
        ),
    ]
