# Generated by Django 4.1.1 on 2023-07-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_directorgeneralmodel_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneralmodel',
            name='especialidad',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='laboratoriomodel',
            name='ciudad',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='laboratoriomodel',
            name='pais',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='productosmodel',
            name='f_fabricacion',
            field=models.DateField(default='2015'),
        ),
    ]
